package ingestor;

public class Event {
    /*
    POJO to store tuple <obj_id, timestamp, latitude, longitude>
    Can be generated by either:
    1. reading from binary files; or 2. generation of fake data;
     */
}
